### ISSUE TITLE
android:dependency doesn't change color of preference

### ISSUE THREAD

**Issue by proninyaroslav** [Gericop/Android-Support-Preference-V7-Fix#178]
This appears in 28.0.0.0-alpha3 version (all Android versions). The dependency works, but it does not affect the color of the preference, it remains externally enabled in view, not disabled.

Log with error:

```
    --------- beginning of system
08-02 14:34:18.900 2866-2866/org.proninyaroslav.libretorrent.debug W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@1bb966f
08-02 14:34:18.920 2866-2866/org.proninyaroslav.libretorrent.debug D/Ringtone: Successfully created local player
08-02 14:34:18.925 2866-2866/org.proninyaroslav.libretorrent.debug I/FloatingActionButton: Setting a custom background is not supported.
08-02 14:34:18.928 2866-2866/org.proninyaroslav.libretorrent.debug W/System.err: java.lang.NoSuchFieldException: No field resId in class Landroid/support/v7/preference/PreferenceGroupAdapter$PreferenceLayout; (declaration of 'android.support.v7.preference.PreferenceGroupAdapter$PreferenceLayout' appears in /data/app/org.proninyaroslav.libretorrent.debug-DHBYSEKW-F8yb_74PKYxPw==/split_lib_dependencies_apk.apk)
        at java.lang.Class.getDeclaredField(Native Method)
        at com.takisoft.fix.support.v7.preference.PreferenceGroupAdapter.getReflectionFields(PreferenceGroupAdapter.java:42)
        at com.takisoft.fix.support.v7.preference.PreferenceGroupAdapter.<init>(PreferenceGroupAdapter.java:33)
        at com.takisoft.fix.support.v7.preference.PreferenceFragmentCompat.onCreateAdapter(PreferenceFragmentCompat.java:68)
        at android.support.v7.preference.PreferenceFragmentCompat.bindPreferences(PreferenceFragmentCompat.java:538)
        at android.support.v7.preference.PreferenceFragmentCompat.onViewCreated(PreferenceFragmentCompat.java:329)
08-02 14:34:18.929 2866-2866/org.proninyaroslav.libretorrent.debug W/System.err:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1471)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2623)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2410)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2365)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2272)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3271)
        at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3227)
        at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:610)
        at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
08-02 14:34:18.930 2866-2866/org.proninyaroslav.libretorrent.debug W/System.err:     at android.app.Activity.performStart(Activity.java:7157)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2937)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by proninyaroslav** [comment]
Sorry, I forgot to inherit `PreferenceFixTheme` style.
