### ISSUE TITLE
android.widget.Switch cannot be cast to android.support.v7.widget.SwitchCompat

### ISSUE THREAD

**Issue by virusman** [Gericop/Android-Support-Preference-V7-Fix#58]
I used to run 23.4.0.2 without problems, but the introduction of SwitchPreferenceCompat since 23.4.0.3 now causes crashes in my app:

```
java.lang.ClassCastException: android.widget.Switch cannot be cast to android.support.v7.widget.SwitchCompat
at com.takisoft.fix.support.v7.preference.SwitchPreferenceCompat.onBindViewHolder(SwitchPreferenceCompat.java:32)
at android.support.v7.preference.PreferenceGroupAdapter.onBindViewHolder(PreferenceGroupAdapter.java:297)
at android.support.v7.preference.PreferenceGroupAdapter.onBindViewHolder(PreferenceGroupAdapter.java:35)

```

**Comment by Gericop** [comment]
Can you provide the preferences XML and the basics of the fragment you use (like which class do you extend)? If the sample app works from here, there might be some mixup in your code / XML. Also, what version of Android it is?

**Comment by virusman** [comment]
It was caused by my own patch of the layout for API 21+ to fix the animations before the fix was available in this library.
