### ISSUE TITLE
Cause build crash with com.android.tools.build:gradle:2.4.0-alpha7

### ISSUE THREAD

**Issue by tprochazka** [Gericop/Android-Support-Preference-V7-Fix#77]
Probably it is bug in the build tools. I don't know yet.
But it happens just with your fix lib, projects without it works correctly.
I just to know if it happens also to you.
I'm trying to found the reason before reporting to adt dev team.

I just created empty demo project in Android Studio 2.4 Preview 7 and added this ad dependency
    compile 'com.android.support:preference-v14:25.3.1'
    compile 'com.takisoft.fix:preference-v7:25.3.1.0'

```
Unable to pre-dex 'C:\Users\tomas\.android\build-cache\b8cf6a325906ec6990b98bebedf83aaccc1956fd\output\jars\classes.jar' to 'C:\PJazyky\_Projekty_com\MyApplication4\app\build\intermediates\transforms\dexBuilder\debug\jars\40000\10\classes_d9d878f628502f2613bb4212d2e3093eaea2055f.jar'

predex will process C:\PJazyky\_Projekty_com\MyApplication4\app\build\intermediates\transforms\instantRunSlicer\debug\folders\1\5\slice_2
predex will process C:\PJazyky\_Projekty_com\MyApplication4\app\build\intermediates\transforms\instantRunSlicer\debug\folders\1\5\slice_3
predex will process C:\PJazyky\_Projekty_com\MyApplication4\app\build\intermediates\transforms\instantRunSlicer\debug\folders\1\5\slice_4

AGPBI: {"kind":"error","text":"Error converting bytecode to dex:\nCause: not found: Ljava/lang/Object;","sources":[{}],"original":"UNEXPECTED TOP-LEVEL EXCEPTION:\nnot found: Ljava/lang/Object;\n","tool":"Dex"}
AGPBI: {"kind":"error","text":"java.lang.RuntimeException: com.android.dex.util.ExceptionWithContext: not found: Ljava/lang/Object;","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.ide.common.internal.WaitableExecutor.waitForTasksWithQuickFail(WaitableExecutor.java:183)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.builder.dexing.DexArchiveBuilder.processOutputs(DexArchiveBuilder.java:95)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.builder.dexing.DexArchiveBuilder.convert(DexArchiveBuilder.java:78)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.build.gradle.internal.transforms.DexArchiveBuilderTransformCallable.lambda$cacheMissAction$0(DexArchiveBuilderTransformCallable.java:239)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.builder.utils.FileCache.lambda$createFile$1(FileCache.java:260)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.builder.utils.FileCache.lambda$null$5(FileCache.java:443)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.builder.utils.SynchronizedFile.doActionWithMultiProcessLocking(SynchronizedFile.java:265)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.builder.utils.SynchronizedFile.write(SynchronizedFile.java:232)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.builder.utils.FileCache.lambda$queryCacheEntry$6(FileCache.java:415)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.builder.utils.SynchronizedFile.doActionWithMultiProcessLocking(SynchronizedFile.java:265)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.builder.utils.SynchronizedFile.read(SynchronizedFile.java:215)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.builder.utils.FileCache.queryCacheEntry(FileCache.java:391)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.builder.utils.FileCache.createFile(FileCache.java:273)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.build.gradle.internal.transforms.DexArchiveBuilderTransformCallable.getFromCacheAndCreateIfMissing(DexArchiveBuilderTransformCallable.java:187)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.build.gradle.internal.transforms.DexArchiveBuilderTransformCallable.call(DexArchiveBuilderTransformCallable.java:149)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.build.gradle.internal.transforms.DexArchiveBuilderTransformCallable.call(DexArchiveBuilderTransformCallable.java:53)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat java.lang.Thread.run(Thread.java:745)","sources":[{}]}
AGPBI: {"kind":"error","text":"Caused by: com.android.dex.util.ExceptionWithContext: not found: Ljava/lang/Object;","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.dex.util.ExceptionWithContext.withContext(ExceptionWithContext.java:45)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.dx.dex.file.DebugInfoItem.place0(DebugInfoItem.java:76)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.dx.dex.file.OffsettedItem.place(OffsettedItem.java:242)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.dx.dex.file.MixedItemSection.placeItems(MixedItemSection.java:311)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.dx.dex.file.DexFile.toDex0(DexFile.java:544)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.dx.dex.file.DexFile.toDex(DexFile.java:215)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.builder.dexing.DexArchiveBuilderCallable.call(DexArchiveBuilderCallable.java:72)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.builder.dexing.DexArchiveBuilderCallable.call(DexArchiveBuilderCallable.java:40)","sources":[{}]}
AGPBI: {"kind":"error","text":"\t... 6 more","sources":[{}]}
AGPBI: {"kind":"error","text":"Caused by: java.lang.IllegalArgumentException: not found: Ljava/lang/Object;","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.dx.dex.file.TypeIdsSection.indexOf(TypeIdsSection.java:167)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.dx.dex.file.TypeIdsSection.indexOf(TypeIdsSection.java:185)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.dx.dex.file.DebugInfoEncoder.emitTypeIndex(DebugInfoEncoder.java:673)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.dx.dex.file.DebugInfoEncoder.emitLocalStart(DebugInfoEncoder.java:704)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.dx.dex.file.DebugInfoEncoder.emitLocalsAtAddress(DebugInfoEncoder.java:326)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.dx.dex.file.DebugInfoEncoder.convert0(DebugInfoEncoder.java:227)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.dx.dex.file.DebugInfoEncoder.convert(DebugInfoEncoder.java:162)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.dx.dex.file.DebugInfoItem.encode0(DebugInfoItem.java:185)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.dx.dex.file.DebugInfoItem.encode(DebugInfoItem.java:141)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.dx.dex.file.DebugInfoItem.place0(DebugInfoItem.java:73)","sources":[{}]}
AGPBI: {"kind":"error","text":"\t... 12 more","sources":[{}]}

:app:transformClassesWithDexBuilderForDebug FAILED
:app:transformClassesWithDexBuilderForDebug (Thread[Daemon worker Thread 7,5,main]) completed. Took 0.13 secs.
:app:buildInfoGeneratorDebug (Thread[Daemon worker Thread 7,5,main]) started.
:app:buildInfoGeneratorDebug
Putting task artifact state for task ':app:buildInfoGeneratorDebug' into context took 0.0 secs.
Executing task ':app:buildInfoGeneratorDebug' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
:app:buildInfoGeneratorDebug (Thread[Daemon worker Thread 7,5,main]) completed. Took 0.004 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDexBuilderForDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: com.android.builder.utils.FileCache$FileCreatorException: com.android.builder.dexing.DexArchiveBuilder$DexBuilderException: Unable to convert input to dex archive.

* Try:
Run with --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformClassesWithDexBuilderForDebug'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:84)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:236)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:228)
	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:228)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:77)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:58)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:32)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:113)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
	at org.gradle.initialization.DefaultGradleLauncher$RunTasksAction.execute(DefaultGradleLauncher.java:256)
	at org.gradle.initialization.DefaultGradleLauncher$RunTasksAction.execute(DefaultGradleLauncher.java:253)
	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:175)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:119)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:102)
	at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:71)
	at org.gradle.tooling.internal.provider.runner.BuildModelActionRunner.run(BuildModelActionRunner.java:50)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.tooling.internal.provider.runner.RunAsBuildOperationBuildActionRunner$1.execute(RunAsBuildOperationBuildActionRunner.java:43)
	at org.gradle.tooling.internal.provider.runner.RunAsBuildOperationBuildActionRunner$1.execute(RunAsBuildOperationBuildActionRunner.java:40)
	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
	at org.gradle.tooling.internal.provider.runner.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:40)
	at org.gradle.tooling.internal.provider.runner.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:75)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:49)
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:31)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:47)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: com.android.builder.utils.FileCache$FileCreatorException: com.android.builder.dexing.DexArchiveBuilder$DexBuilderException: Unable to convert input to dex archive.
	at com.android.builder.profile.Recorder$Block.handleException(Recorder.java:55)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:104)
	at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:186)
	at sun.reflect.GeneratedMethodAccessor425.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:163)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
	... 81 more
Caused by: com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: com.android.builder.utils.FileCache$FileCreatorException: com.android.builder.dexing.DexArchiveBuilder$DexBuilderException: Unable to convert input to dex archive.
	at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.transform(DexArchiveBuilderTransform.java:205)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:195)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:191)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
	... 91 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: com.android.builder.utils.FileCache$FileCreatorException: com.android.builder.dexing.DexArchiveBuilder$DexBuilderException: Unable to convert input to dex archive.
	at com.android.ide.common.internal.WaitableExecutor.waitForTasksWithQuickFail(WaitableExecutor.java:183)
	at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.transform(DexArchiveBuilderTransform.java:198)
	... 94 more
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: com.android.builder.utils.FileCache$FileCreatorException: com.android.builder.dexing.DexArchiveBuilder$DexBuilderException: Unable to convert input to dex archive.
	at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransformCallable.getFromCacheAndCreateIfMissing(DexArchiveBuilderTransformCallable.java:194)
	at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransformCallable.call(DexArchiveBuilderTransformCallable.java:149)
	at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransformCallable.call(DexArchiveBuilderTransformCallable.java:53)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: com.android.builder.utils.FileCache$FileCreatorException: com.android.builder.dexing.DexArchiveBuilder$DexBuilderException: Unable to convert input to dex archive.
	at com.android.builder.utils.SynchronizedFile.doActionWithMultiProcessLocking(SynchronizedFile.java:267)
	at com.android.builder.utils.SynchronizedFile.read(SynchronizedFile.java:215)
	at com.android.builder.utils.FileCache.queryCacheEntry(FileCache.java:391)
	at com.android.builder.utils.FileCache.createFile(FileCache.java:273)
	at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransformCallable.getFromCacheAndCreateIfMissing(DexArchiveBuilderTransformCallable.java:187)
	... 8 more
Caused by: java.util.concurrent.ExecutionException: com.android.builder.utils.FileCache$FileCreatorException: com.android.builder.dexing.DexArchiveBuilder$DexBuilderException: Unable to convert input to dex archive.
	at com.android.builder.utils.SynchronizedFile.doActionWithMultiProcessLocking(SynchronizedFile.java:267)
	at com.android.builder.utils.SynchronizedFile.write(SynchronizedFile.java:232)
	at com.android.builder.utils.FileCache.lambda$queryCacheEntry$6(FileCache.java:415)
	at com.android.builder.utils.SynchronizedFile.doActionWithMultiProcessLocking(SynchronizedFile.java:265)
	... 12 more
Caused by: com.android.builder.utils.FileCache$FileCreatorException: com.android.builder.dexing.DexArchiveBuilder$DexBuilderException: Unable to convert input to dex archive.
	at com.android.builder.utils.FileCache.lambda$createFile$1(FileCache.java:262)
	at com.android.builder.utils.FileCache.lambda$null$5(FileCache.java:443)
	at com.android.builder.utils.SynchronizedFile.doActionWithMultiProcessLocking(SynchronizedFile.java:265)
	... 15 more
Caused by: com.android.builder.dexing.DexArchiveBuilder$DexBuilderException: Unable to convert input to dex archive.
	at com.android.builder.dexing.DexArchiveBuilder.convert(DexArchiveBuilder.java:88)
	at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransformCallable.lambda$cacheMissAction$0(DexArchiveBuilderTransformCallable.java:239)
	at com.android.builder.utils.FileCache.lambda$createFile$1(FileCache.java:260)
	... 17 more
Caused by: com.android.dex.util.ExceptionWithContext: not found: Ljava/lang/Object;
	at com.android.dex.util.ExceptionWithContext.withContext(ExceptionWithContext.java:45)
	at com.android.dx.dex.file.DebugInfoItem.place0(DebugInfoItem.java:76)
	at com.android.dx.dex.file.OffsettedItem.place(OffsettedItem.java:242)
	at com.android.dx.dex.file.MixedItemSection.placeItems(MixedItemSection.java:311)
	at com.android.dx.dex.file.DexFile.toDex0(DexFile.java:544)
	at com.android.dx.dex.file.DexFile.toDex(DexFile.java:215)
	at com.android.builder.dexing.DexArchiveBuilderCallable.call(DexArchiveBuilderCallable.java:72)
	at com.android.builder.dexing.DexArchiveBuilderCallable.call(DexArchiveBuilderCallable.java:40)
	... 6 more
Caused by: java.lang.IllegalArgumentException: not found: Ljava/lang/Object;
	at com.android.dx.dex.file.TypeIdsSection.indexOf(TypeIdsSection.java:167)
	at com.android.dx.dex.file.TypeIdsSection.indexOf(TypeIdsSection.java:185)
	at com.android.dx.dex.file.DebugInfoEncoder.emitTypeIndex(DebugInfoEncoder.java:673)
	at com.android.dx.dex.file.DebugInfoEncoder.emitLocalStart(DebugInfoEncoder.java:704)
	at com.android.dx.dex.file.DebugInfoEncoder.emitLocalsAtAddress(DebugInfoEncoder.java:326)
	at com.android.dx.dex.file.DebugInfoEncoder.convert0(DebugInfoEncoder.java:227)
	at com.android.dx.dex.file.DebugInfoEncoder.convert(DebugInfoEncoder.java:162)
	at com.android.dx.dex.file.DebugInfoItem.encode0(DebugInfoItem.java:185)
	at com.android.dx.dex.file.DebugInfoItem.encode(DebugInfoItem.java:141)
	at com.android.dx.dex.file.DebugInfoItem.place0(DebugInfoItem.java:73)
	... 12 more

```

**Comment by tprochazka** [comment]
I created gradle plugin issue too
https://issuetracker.google.com/issues/38105043

**Comment by Gericop** [comment]
Did you try the same thing with adding a different lib as a dependency and leaving mine out? I've had this problem with different libs too, and it appears to be an issue with gradle. If it works with another libs, I could imagine that the v25 vs v26 thing could cause trouble here but it seems to me that it's not unique.

**Comment by Gericop** [comment]
Removed some old files, not it seems to be working for me. Could you test it @tprochazka with v25.3.1.1?

**Comment by Schinizer** [comment]
` v25.3.1.1` seems to work for me. I'm using ` com.android.tools.build:gradle:3.0.0-alpha1`

**Comment by tprochazka** [comment]
Yes. 25.3.1.1 really works also without fix on google side. Great job!!!
