### ISSUE TITLE
NullPointerException EditTextPreference

### ISSUE THREAD

**Issue by woodii** [Gericop/Android-Support-Preference-V7-Fix#89]
Hey,

currently i am dealing with a strange bug which i unfortunately cannot reproduce. For some reason one of your internal methods returns null and the app crashes.
According to your code this.getPreference() must be null in [EditTextPreferenceDialogFragmentCompat ](https://github.com/Gericop/Android-Support-Preference-V7-Fix/blob/master/preference-v7/src/main/java/com/takisoft/fix/support/v7/preference/EditTextPreferenceDialogFragmentCompat.java), which sounds kinda strange to me.

Any idea when this could happen or how to avoid that?
Would appreciate any help on this case. Thank you in advance!

> Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{<package>/<package>.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.widget.EditText com.takisoft.fix.support.v7.preference.EditTextPreference.l()' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3912)
       at android.app.ActivityThread.access$900(ActivityThread.java:144)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1284)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5221)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'android.widget.EditText com.takisoft.fix.support.v7.preference.EditTextPreference.l()' on a null object reference
       at com.takisoft.fix.support.v7.preference.EditTextPreferenceDialogFragmentCompat.onBindDialogView(SourceFile:48)
       at android.support.v7.preference.PreferenceDialogFragmentCompat.onCreateDialog(SourceFile:148)
       at android.support.v4.app.DialogFragment.getLayoutInflater(SourceFile:312)
       at android.support.v4.app.FragmentManagerImpl.moveToState(SourceFile:1299)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(SourceFile:1528)
       at android.support.v4.app.FragmentManagerImpl.moveToState(SourceFile:1595)
       at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(SourceFile:2900)
       at android.support.v4.app.FragmentController.dispatchActivityCreated(SourceFile:201)
       at android.support.v4.app.FragmentActivity.onStart(SourceFile:603)
       at android.support.v7.app.AppCompatActivity.onStart(SourceFile:178)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1220)
       at android.app.Activity.performStart(Activity.java:5992)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2261)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3912)
       at android.app.ActivityThread.access$900(ActivityThread.java:144)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1284)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5221)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)

**Comment by Gericop** [comment]
Is it possible that the ProGuard removes something necessary?

**Comment by woodii** [comment]
it only happens a few times and for very few users. i could try to exclude your library from the obfuscation and see if it still happens.

**Comment by Gericop** [comment]
If it happens only for a few users, it's probably not ProGuard problem. Do you know anything more about the events before this? Like, is the device rotated right before it? What Android version? Is this happening when the user explicitly clicks on the preference or you perform a click?

**Comment by woodii** [comment]
Sorry for the late response - I was on vacation for several days. 
Unfortunately not. Thats why i hoped you have any idea. Otherwise i can only implement several traces and try to reproduce it.

**Comment by Gericop** [comment]
Cannot reproduce.

**Comment by CyberShadow** [comment]
Happens with official AndroidX preference 1.1.0. To reproduce, open an EditText preference, then rotate the screen **twice**.

**Comment by gregkorossy** [comment]
@CyberShadow Cannot reproduce with 1.1.0 no matter how many times the screen is rotated. What Android version / what device do you use?

**Comment by CyberShadow** [comment]
Seeing it in an API 15 emulator. Maybe there is more to it, will try to make a minimal project.
(Note: did not try with this library, trying to resolve the crash with official AndroidX right now, this issue looks very similar.)
Edit: Oops, actually I'm getting "Target fragment must implement TargetFragment interface" (also unhandled exception), which is caused by `getTargetFragment()` returning `null` in `PreferenceDialogFragmentCompat.onCreate`. Might be the same root cause.

**Comment by CyberShadow** [comment]
https://issuetracker.google.com/issues/146166988

**Comment by gregkorossy** [comment]
@CyberShadow The linked repo seems to be private.

**Comment by CyberShadow** [comment]
Thank you for letting me know, fixed :)

**Comment by CyberShadow** [comment]
@Gericop, did you by any chance look into this?

I'm seeing some really serious bugs in Google's AndroidX library. I'm just starting out in Android development, so I don't know if I'm doing something wrong or the library is just super-buggy. The other bug I've found is that upon rotation, `onCreatePreferences` is called twice when the device is rotated. The second time, the `savedInstanceState` bundle is `null`, so there's no way to restore the fragment state to the way it was before. Even crazier, when I attempted to work around this by saving the bundle to a static variable, I found that the static variable is nulled out between these two calls! You can reproduce this in the `TextEditCrashSample` app I posted, just set a breakpoint on `SettingsActivity.SettingsFragment.onCreatePreferences` and watch the `savedInstanceState` parameter when rotating the screen.

**Comment by gregkorossy** [comment]
@CyberShadow I think you have a problem in your `SettingsActivity`. On each rotation you basically create a new `SettingsFragment` which replaces the previous one and I think this is the cause of your crashes.
What you should do is check whether you need to add (replace) the `SettingsFragment` into the activity, i.e. check if `savedInstanceState` in your activity's `onCreate(...)` is `null`:

```java
if (savedInstanceState == null) {
    getSupportFragmentManager()
        .beginTransaction()
        .replace(R.id.settings, new SettingsFragment())
        .commit();
}

```

**Comment by CyberShadow** [comment]
That code was generated by Android Studio and I did not change it.

I'll try your suggestion.

**Comment by CyberShadow** [comment]
Seems to work... thank you! Hopefully we can rely on AndroidX correctly restoring the fragment to the correct state. I guess the IDE template is outdated or something.
Edit: Wow, this also fixes the EditText crash, fantastic :)
