### ISSUE TITLE
id not found issue - android.R.id.list_container

### ISSUE THREAD

**Issue by hoelee** [Gericop/Android-Support-Preference-V7-Fix#91]
I'm tested below version, all the same exception come out
com.takisoft.fix:preference-v7:25.0.1.0
com.takisoft.fix:preference-v7:26.0.2.0
Any idea? Only me facing this?

Caused by: java.lang.RuntimeException: Content has view with id attribute 'android.R.id.list_container' that is not a ViewGroup class
                                                                         at android.support.v7.preference.PreferenceFragmentCompat.onCreateView(PreferenceFragmentCompat.java:269)
                                                                         at com.hoelee.supersip.fragment.MyPreferenceFragment.onCreateView(MyPreferenceFragment.java:33)
                                                                         at android.support.v4.app.Fragment.performCreateView(Fragment.java:2087)
                                                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1113)
                                                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1295)
                                                                         at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
                                                                         at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1682)
                                                                         at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
                                                                         at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607)
                                                                         at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:181)
                                                                         at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1265)
                                                                         at android.app.Activity.performStart(Activity.java:6915)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3217)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350) 
                                                                         at android.app.ActivityThread.access$1100(ActivityThread.java:222) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                         at android.os.Looper.loop(Looper.java:158) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:7229) 
                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by Gericop** [comment]
Are you overriding anything in the styles? Like the `layout` attribute in your theme.

**Comment by Gericop** [comment]
I'm closing this issue as it seems to be a setup error rather than a bug in the library.
